### ISSUE TITLE
Sending smart transactions inside a thread fails to compile

### ISSUE THREAD

**Issue by makovkins** [helius-labs/helius-rust-sdk#102]
Hello,
I want to send a smart transaction inside a thread spawned by tokio::spawn but it fails to compile:
```
async fn example_send_smart_transaction_with_tip() {
    tokio::spawn(async {
        let api_key: &str = "YOUR_API_KEY";
        let cluster: Cluster = Cluster::MainnetBeta;
        let helius: Helius = Helius::new(api_key, cluster).unwrap();

        // ................

        helius.send_smart_transaction_with_tip(config, Some(10000), Some("NY")).await

        // ................

});
}
```

Here is the error i get:
```
 the trait `Sync` is not implemented for `(dyn solana_sdk::signature::Signer + 'static)`
```

Is there any way to use helius client inside a thread?
[send_smart_transaction_with_tip.txt](https://github.com/user-attachments/files/18218502/send_smart_transaction_with_tip.txt)

**Comment by 0xIchigo** [comment]
gm! You're going to want to look at the [`send_smart_transaction_with_seeds` function](https://github.com/helius-labs/helius-rust-sdk/blob/a6a16c594c1de615a6217069a5067ffa52c1ba6f/src/optimized_transaction.rs#L420-L494). This will allow you to send transactions where the `Signer` trait's lack of `Send` + `Sync` would otherwise cause issues

I can also open up a PR to have a `send_smart_transaction_with_seeds_with_tip` function, or something to that effect, if that works

**Comment by makovkins** [comment]
send_smart_transaction_with_seeds() has the same issue. Here is an example. Try it, please.

```
async fn example_send_smart_transaction() {
    tokio::spawn(async {
        let helius = Helius::new("YOUR_API_KEY", Cluster::MainnetBeta).unwrap();

        let create_config = CreateSmartTransactionSeedConfig {
            instructions : vec![],
            signer_seeds: vec![],
            lookup_tables: None,
            priority_fee_cap: None,
            fee_payer_seed: None,
        };

        helius.send_smart_transaction_with_seeds(create_config, None, None).await.unwrap();
    });
}
```

Why don't you sing the transaction using new_signed_with_payer()?
```
  let payer = Keypair::new();
  let transaction = Transaction::new_signed_with_payer(&instructions, Some(&payer.pubkey()), &[payer], recent_blockhash);
```
This method works fine in any thread.
