### ISSUE TITLE
Improved Test Coverage

### ISSUE THREAD

**Issue by 0xIchigo** [helius-labs/helius-rust-sdk#15]
Currently, the Enhanced Transactions API and webhooks do not have any tests to ensure they work as intended. We've tested them using real-world calls; however, this isn't enough. We need to add tests for the following methods:
- `parse_transactions`
- `parsed_transaction_history`
- `append_addresses_to_webhook`
- `create_webhook`
- `delete_webhook`
- `edit_webhook`
- `get_all_webhooks`
- `get_webhook_by_id`
- `remove_addresses_from_webhook`

**Comment by davidkathoh** [comment]
@0xIchigo  would you please assign  me this issue

**Comment by 0xIchigo** [comment]
@davidkathoh go for it! 🔥

**Comment by 0xIchigo** [comment]
Closed by #24
