### ISSUE TITLE
Add `delegate_collection_authority`

### ISSUE THREAD

**Issue by 0xIchigo** [helius-labs/helius-rust-sdk#16]
In our Node.js SDK, we have the [`delegateCollectionAuthority` method](https://github.com/helius-labs/helius-sdk/blob/2a50e1ce6b33730134e2422723aa7c98265fbcd5/src/Helius.ts#L409-L467), which delegates a collection authority to a new address. This is handy when used with our Mint API. We should add this functionality to the Rust SDK

**Comment by davidkathoh** [comment]
Can you add assign this to me?

**Comment by 0xIchigo** [comment]
@davidkathoh go for it!
