### ISSUE TITLE
Add `revoke_collection_authority`

### ISSUE THREAD

**Issue by 0xIchigo** [helius-labs/helius-rust-sdk#17]
In our Node.js SDK, we have the [`revokeCollectionAuthority` method](https://github.com/helius-labs/helius-sdk/blob/2a50e1ce6b33730134e2422723aa7c98265fbcd5/src/Helius.ts#L469-L525), which revokes collection authority from an address. This is handy when used with our Mint API. We should add this functionality to the Rust SDK

**Comment by davidkathoh** [comment]
Can you assign this to me?

**Comment by grandima** [comment]
I tried to dig into this issue and I found that Node.js SDK uses Metaplex to make NFT requests under the hood. Should the solution to this issue rely on some Rust alternative library to Metaplex or write all the necessary code (structs, requests) in Rust SDK library?

**Comment by 0xIchigo** [comment]
@grandima, I haven't dug into it yet so I'm not 100% sure. It hasn't been a huge priority, so it's your call — whatever works best!

**Comment by grandima** [comment]
@0xIchigo hey! The PR is ready. Feel free to review. Also I can take over #16, because current PR already uses some features from #16.

**Comment by 0xIchigo** [comment]
Can we considered closed now that #77 has been merged
