### ISSUE TITLE
Improve handle_response to handle empty  response  body Scenarios

### ISSUE THREAD

**Issue by davidkathoh** [helius-labs/helius-rust-sdk#25]
### Current Behavior:
The `handle_response` function fails to parse JSON from an empty response body, resulting in a deserialization error.

### Problem:
When making a successful HTTP request to `delete_webhook`, the response returns an empty body. `handle_response` is unable to handle this scenario, causing it to throw a deserialization error.

### Expected Behavior:
The `handle_response` function should be able to gracefully handle empty response bodies without throwing errors, especially in cases where a successful HTTP request returns an empty body, such as with `delete_webhook`.

**Comment by 0xIchigo** [comment]
Thanks for another good catch! This issue is closed with #28
