### ISSUE TITLE
Fix URL Formatting Issues

### ISSUE THREAD

**Issue by davidkathoh** [helius-labs/helius-rust-sdk#26]
**Current Behavior:**
The `edit_webhook`, `delete_webhook`, and `get_webhook_by_id` functions use the following URL format:
```
"{}v0/webhooks/{}/?api-key={}"
```
This causes these function calls to fail.

**Problem:**
The current URL format includes an unnecessary slash before the webhook_id  query parameter, leading to incorrect URLs and failed function calls.

**Expected Behavior:**
The functions should use the correct URL format:
```
"{}v0/webhooks/{}?api-key={}"
```
With this format, the functions should successfully call the webhooks API without errors.

**Comment by 0xIchigo** [comment]
Thanks for catching this! It has been closed with #27
