### ISSUE TITLE
Is this renaming correct?

### ISSUE THREAD

**Issue by cpkt9762** [helius-labs/helius-rust-sdk#33]
helius\src\types\types.rs 353
#[serde(rename = "tokenSupply")]
    pub token_info: Option<TokenInfo>,

"Use solana_client::rpc_client::RpcClient;" can be replaced by
"Use solana_client::nonblocking::rpc_client::RpcClient;" Use asynchronous RpcClient?

**Comment by 0xIchigo** [comment]
Sorry, are these two separate questions? Yes, we could use the async RpcClient instead to keep everything async. I've been meaning to look into Solana's async client more, but I've been swamped with other work. I initially used the synchronous client to get everything up and running as fast as possible, but it would make sense to switch it over

**Comment by 0xIchigo** [comment]
I'm going to open a PR so the embedded Solana client defaults to the async client and then introduce a new function that'll allow users to create with a synchronous Solana client if they'd like. Thanks for pointing this out!
