### ISSUE TITLE
EditWebhookRequest incorrectly includes webhook_id in body, and is not camelCased

### ISSUE THREAD

**Issue by luca992** [helius-labs/helius-rust-sdk#52]
See [here](https://github.com/helius-labs/helius-rust-sdk/blob/dc1fd1a7de76039ac670cf4a916720e991f5dea9/src/types/types.rs#L932)
https://docs.helius.dev/webhooks-and-websockets/api-reference/edit-webhook

This error is returned:

```
{
    "error": "invalid request payload: unknown field 'webhookID'"
}
```

additionally, it's not camelCased. 

Edit: I just fixed this on my fork I'll make another pr.

**Comment by 0xIchigo** [comment]
This PR can be considered closed, and resolved by, #53
