### ISSUE TITLE
about sync + send

### ISSUE THREAD

**Issue by w6g2000** [helius-labs/helius-rust-sdk#61]
"When I used the send_smart_transaction method, I found that the parameter trait Signer does not implement Sync + Send, so it cannot be used in asynchronous tasks. To avoid this issue, would it be possible to pass in a parameter that allows the construction of a Keypair so that the Keypair can be constructed internally within the method to avoid this problem?"

**Comment by 0xIchigo** [comment]
gm @w6g2000! I apologize for taking a minute to get around to this issue, but would #64 resolve this issue?
