### ISSUE TITLE
Update to solana 2.0 sdk

### ISSUE THREAD

**Issue by luca992** [helius-labs/helius-rust-sdk#72]
Can't use the latest release with the latest solana-* 2.0.0 crates

**Comment by mahmudsudo** [comment]
can i take on this?

**Comment by luca992** [comment]
What is there to take on.... you change the number from 1 to 2... https://github.com/luca992/helius-rust-sdk/commit/9a78c68c8cfc0d8dfe9f0689342bf1cf4a44f8e5

**Comment by 0xIchigo** [comment]
Can be considered closed by #80
