### ISSUE TITLE
Rework `CreateSmartTransactionConfig` to Resolve Lifetime Issues

### ISSUE THREAD

**Issue by 0xIchigo** [helius-labs/helius-rust-sdk#83]
The lifetime parameter on `CreateSmartTransactionConfig` is required because it contains references to signers and instructions. This has the potential to create several issues and should be avoided. We should rework this to avoid any potential lifetime issues.

An arc-based solution is probably best as no lifetime parameters are needed, it's thread-safe, and it shares ownership efficiently. The only downside is a slight runtime overhead from reference counting and then the need to wrap signers in an arc when creating the config. A builder pattern solution is also a possibility, but then we introduce a lot of boilerplate, and a clone-based solution would require signers to implement clone

**Comment by mahmudsudo** [comment]
Hi , can i take up this role ?

**Comment by 0xIchigo** [comment]
gm @mahmudsudo! For sure, go for it!

**Comment by mahmudsudo** [comment]
on it

**Comment by sarmatdev** [comment]
Hey @mahmudsudo, any luck on this one?
